version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tp3bd3_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - tp3bd3-network

    healthcheck:
      test: ["CMD-SHELL",
             "PGPASSWORD=$${POSTGRES_PASSWORD} pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    container_name: tp3bd3_java
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - tp3bd3-network

networks:
  tp3bd3-network:
    driver: bridge
