version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tp3bd3_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - tp3bd3-network

  app:
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    container_name: tp3bd3_java
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - tp3bd3-network

networks:
  tp3bd3-network:
    driver: bridge
