version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tp3bd3_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    networks:
      - tp3bd3-network

  app:
    build:
      context: ../
      dockerfile: docker/java/Dockerfile
    container_name: tp3bd3_java
    depends_on:
      - postgres
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - tp3bd3-network


networks:
  tp3bd3-network:
    driver: bridge
